### PR TITLE
Fix for assembly link issue #21

### PR DESCRIPTION
**Pull request by JoshuaNovak919**
Fixes the issue causing release builds to not work properly when using the default build option `Link SDK assemblies only`.

### CODE REVIEW

**Comment by JoshuaNovak919** [comment]
Is this going to be merged at some point or do we not want to fix this issue?

**Comment by chrfalch** [comment]
@JoshuaNovak919: Yes, we can merge this, I was just waiting for some more information in the discussion you had with @BlueRaja about some of the details in the merge. 

Another issue is that I need to fix this for the Windows components in the library which was not included in your pull request - Unfortunately I haven't had the time to do this yet.

**Comment by OpticNectar** [comment]
@chrfalch Any update on this. All you have to do is build your demo project for release with `Link SDK assemblies only` (the recommended setting) and you'll see the controls don't show up.

**Comment by JoshuaNovak919** [comment]
@chrfalch Any update on this. All you have to do is build your demo project for release with `Link SDK assemblies only` (the recommended setting) and you'll see the controls don't show up.

**Comment by chrfalch** [comment]
Done!

**Pull request closed without merging**
