### PR TITLE
UWP Support

### PR DESCRIPTION
**Pull request by TomSoderling**
This is my attempt at support for Universal Windows Platform (UWP).
I followed a pretty basic monkey-see, monkey-do approach and added a new NControl.UWP project which mirrors the implementation for the WinRT platform, and seems to work well on UWP also.  We've been using this in our Xamarin.Forms app on UWP for 6 months now and now that the app was just accepted to the Windows Store, I figured this was a good time to do a PR.

Naturally, this PR depends on my waiting UWP-Support PR for NGraphics. For now, I've included the recompiled NGraphics dlls for UWP that I reference in the NControl and NControl.UWP projects in a folder named "UWP_NGraphics_Assemblies" at the solution root.

As part of my NGraphics PR I updated all its SharpDX libraries to v3.1.0 that was just released, so this might be a good time to do the same for NControl?
I also noticed the version of Xamarin.Forms that this library is using is a few versions behind: v2.2.0.45 from 5/30/2016.  I kept the NControl.UWP library at the latest Xamarin.Forms version since that is what our app is using.  Not sure what the implications of that will be.

I included an important note in the readme file related to using NControl in XF app for UWP.
I believe VS 2015 update 3 is required to open and run the UWP project

Let me know if I screwed something up and I'll try to fix it

### CODE REVIEW

**Comment by TomSoderling** [comment]
Dependent NGraphics PR: https://github.com/praeclarum/NGraphics/pull/63

**Comment by laarmen** [comment]
You shouldn't bump the dependencies without reason. A lower dependency doesn't preclude you from using a newer version.

**Comment by TomSoderling** [comment]
@laarmen Thanks for taking a look at this.  Can you explain your comment a little more?  I'm not sure which dependency you're referring to.

**Comment by laarmen** [comment]
I must have dreamt it, sorry.

**Comment by laarmen** [comment]
OK, this one for sure, you shouldn't add the NGraphics DLL directly in the source tree. Just leave a comment on the PR saying that it shouldn't be merged until praeclarum/NGraphics#63 has been merged and a new nuget has been published (to have a dependency version)

**Comment by TomSoderling** [comment]
Hmmm, I'm not sure what the best way to handle this is.  I did in fact include a note about this in this PR:

> Naturally, this PR depends on my waiting UWP-Support PR for NGraphics. For now, I've included the recompiled NGraphics dlls for UWP that I reference in the NControl and NControl.UWP projects in a folder named "UWP_NGraphics_Assemblies" at the solution root.

I did this to isolate the changes I made for NControl from the ones I made to NGraphics.  I wanted to allow the maintainers and others to be able to test this without needing to also compile NGraphics with my PR (which honestly, I'm not even sure is necessary now based on praeclarum's initial comments about my PR).

**Comment by TomSoderling** [comment]
Good news! The required [NGraphics PR](https://github.com/praeclarum/NGraphics/pull/63) was just merged. Hopefully that will be released soon and this PR can the move forward.
Once NGraphics is released, we'll want to be sure to remove references to the included NGraphis DLLs in this PR. See above [comment](https://github.com/chrfalch/NControl/pull/71#issuecomment-259848231)

**Comment by chrfalch** [comment]
Anyone knows anything about the expected release date for the updated NGraphics?

**Comment by TomSoderling** [comment]
No - I just hit Frank up on Twitter.

**Comment by fotiDim** [comment]
@TomSoderling  any update on this?

**Comment by TomSoderling** [comment]
@fotiDim I've had no response from the NGraphics library guy, so Chris and I have discussed just releasing this ahead of NGraphics - which I'm all for.  I want to encourage any developer to build Xamarin.Forms apps on UWP. 
You can get the code for the pull request, compile, and use the library today.  That's what I'm doing.  Feel free to contact me with questions.

**Comment by BlueRaja** [comment]
If you compile against .Net Standard, you get UWP and .Net Framework (and .Net Core!) support without needing separate projects
.Net Standard Chart

....at least, from what I've read.  I haven't tried it yet.

**Comment by chrfalch** [comment]
What I suggest is that someone takes upon the task to fork NGraphics and
release a new version that can be included with NControl.

Alternatively one could create a new version of NControl that uses
SkiaSharp as the rendering engine. Any thoughts?

Chris

**Comment by fotiDim** [comment]
I think if the original NGraphics is unmaintained a fork is more appropriate.
@chrfalch what benefits do you have in mind regarding SkiaSharp?

**Comment by chrfalch** [comment]
The best would definitely be NGraphics, I just wanted to raise the issue with SkiaSharp - which is supported and maintained by Xamarin and looks more promising.

**Comment by dapug** [comment]
Seriously guys, I'm not even sure it's a question.  NGraphics is dead, SkiaSharp is the officially supported way forward (and has come impressively far in short time), which also means NGraphics is not worth forking.  

Wrap that like you did NGraphics, and you're done.  The bindable controls that NControl provided would be handy compared to just using SkiaSharp as-is.

**Comment by chrfalch** [comment]
Anyone else have strong opinions on this? Wouldn't be hard to convert it,
and would also make some sense. I've made a new issue on Github about this:

https://github.com/chrfalch/NControl/issues/75

**Comment by fotiDim** [comment]
Having considered the facts I am voting as well for SkiaSharp port.

**Comment by TomSoderling** [comment]
juat wanted to mention this since I'm no graphics master. I asked Mark Smith (Xam U) about SkiaSharp vs. NGraphics last year after Evolve. He reached out to his Xamarin coworkers at that time and this is what he said: 

Ultimately, I think the choice is really up to you. The difference is the SkiaSharp was built by Xamarin directly (e.g. the wrapper) - NGraphics was not (it was actually built by Frank Krueger, who is awesome, but not employed by Xamarin).

Miguel had a quote which I think helps explain it a bit from here: https://blog.xamarin.com/cross-platform-2d-graphics-with-skiasharp/

Why We Chose Skia
While Mono has supported System.Drawing for a while, and we built a CoreGraphics-powered version for Mac/iOS, it has never been a pixel-perfect match for the original .NET implementation of System.Drawing. Mono.Cairo is also generally available, but has some limitations that are difficult to work around.

Skia gives us the same graphics output across all platforms, is actively maintained, and offers great features not found elsewhere, like filters and hardware accelerated graphics.

So you can use either wrapper library - and if you have a heavy investment in NGraphics already (which you do), it’s probably not worth moving away from it. For a new project, I’d probably push you towards Skia just because it will have the full support of the Xamarin team going forward and so you can expect to see further improvements and contributions to flesh out the library.

I hope that helps!

**Comment by chrfalch** [comment]
You might consider continuing the discussion here, @TomSoderling : https://github.com/chrfalch/NControl/issues/75

**Comment by gabornemeth** [comment]
FYI: I have created a UWP sample, based on work of @TomSoderling. Consolidated dependencies, too.
If you are interested, you can check [uwp branch of my fork](https://github.com/gabornemeth/NControl/tree/uwp).
Please let me know, whether you consider merging. Otherwise i can still create my private packages as I need this functionality.

**Comment by charlesroddie** [comment]
You will lose Windows 8 support by porting to SkiaSharp [https://github.com/mono/SkiaSharp/issues/20](url) .

So if the port is done, it's worth making a note that people should use an old version for Win8 support, or a forked old version for both Win8 and UWP support.

**Comment by gabornemeth** [comment]
Meanwhile I updated the [uwp branch of my fork](https://github.com/gabornemeth/NControl/tree/uwp) to use NGraphics 0.5.0-beta1. All the SharpDX related errors and warnings have gone now, though here is no more support of Windows (Phone) 8 and 8.1. NGraphics no longer supports them.
If somebody interested, I uploaded a NuGet package to myget - it can be grabbed from [this feed](https://www.myget.org/F/nrglabz/api/v3/index.json).

**Comment by pfaucon** [comment]
Is there any news on this pr? I just started working with a UWP project and had to track down a failure relating to our internal library relying on ncontrol and ngraphics, and if you don't manually install ngraphics first there is a cryptic failure with the package restoration.  At the very least an update nuget package that requires SharpDX 3.11+( or the NGraphics.UWP for UWP projects) would at least allow the packages to install correctly.

**Comment by chrfalch** [comment]
Hi,

Thanks for reaching out. This repository is no longer actively maintained.
Please feel free to fork and update if you want.

Chris

On Sat, Feb 24, 2018 at 3:19 PM, Christophe Faucon <notifications@github.com

**Pull request closed without merging**
